baseURL = 'https://duhh.tech'
languageCode = 'en-us'
title = 'Shuvrojit Biswas'

theme = "themes"
author = "Shuvrojit Biswas"

# enableGitInfo = true

[Author]
name = "Shuvrojit Biswas"


# [Params.source]
# url = "https://gitlab.com/winny.tech/winny.tech"
# commit_base = "https://gitlab.com/winny.tech/winny.tech/-/commit/"
# md_dir = "content"
# org_dir = "content-org"

# [Params.paginate]
# enable = false

[Params]
# coverPrefix = "/ox-hugo/"
googleAnalytics = "G-6T5CCL4346"
links = [
      {url="https://twitter.com/shuv40", text="@shuv40"},
]

[markup.goldmark.renderer]
unsafe = true  # for #+html:

# [build]
# writeStats = true
# 
# [outputs]
# home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = 'categories'
  tag = 'tags'


[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4


[outputs]
  home = ["HTML", "RSS", "JSON"]
